ci: overhaul GH action workflows and simplify them [INTERNAL]
Merge twister workflows for both xcc and gcc into one using a 2
dimensional matrix.
Cleanup overall layout and syntax and generalize where possible, so we
can use the same steps elsewhere.

Signed-off-by: Anas Nashif <anas.nashif@intel.com>

diff --git a/.github/workflows/intel_compliance.yml b/.github/workflows/intel_compliance.yml
--- a/.github/workflows/intel_compliance.yml
+++ b/.github/workflows/intel_compliance.yml
@@ -3,8 +3,10 @@
 #
 # 1. Sets up environment. Installing required deps and clearing out old files
 # 2. Checks out code from internal PR and performs a rebase and west update
-# 3. Runs various compliance checks just like upstream project except we omit the codeowners check internally
-# 4. If any checks fails returns what has failed as well as uploads the .xml file as an artifact to the job
+# 3. Runs various compliance checks just like upstream project except we omit
+#    the codeowners check internally
+# 4. If any checks fails returns what has failed as well as uploads the .xml
+#    file as an artifact to the job
 
 name: Intel Compliance Checks
 
@@ -35,7 +37,6 @@ jobs:
       - name: Checkout the code
         uses: actions/checkout@v3.1.0
         with:
-          path: 'zephyrproject/zephyr'
           ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: 0
 
@@ -47,47 +48,59 @@ jobs:
           pip3 install python-magic junitparser==2.7.0 gitlint pylint pykwalify
           pip3 install west
 
-      # Rebase on origin and run west init->update
-      - name: west setup
+      - name: Set Creds for internal repos
+        run: |
+          touch $HOME/.git-credentials
+          touch $HOME/.gitconfig
+          git config --global user.email "sys_tmbuild@intel.com"
+          git config --global user.name "Github Builder CI"
+          git config --global credential.helper 'store --file=$HOME/.git-credentials'
+          west init -l . || true
+          # Using west, add all internal repos to credentials file.
+          for r in `west  list -f {url} | grep intel-innersource | sed 's#https://##'`; do
+            echo -e "https://$TOKEN:$TOKEN@$r" >> $HOME/.git-credentials
+          done
+          # debug
+          cat $HOME/.git-credentials
+          git config --global --add safe.directory ${PWD}
+
+      - name: Environment Setup
         env:
           BASE_REF: ${{ github.base_ref }}
         run: |
-          cd zephyrproject/zephyr
-          git config --global user.email "you@example.com"
-          git config --global user.name "Your Name"
-          git remote -v
           git rebase origin/${BASE_REF}
           # debug
           git log  --pretty=oneline | head -n 10
-          west init -l . || true
+          west config --global update.narrow true
           west update 2>&1 1> west.update.log || west update 2>&1 1> west.update2.log
+          west forall -c 'git reset --hard HEAD'
 
-      # Run ./scripts/ci/check_compliance.py (maintained upstream) with the same checkers as the project except for codeowners as this will not apply internally
+      # Run ./scripts/ci/check_compliance.py (maintained upstream) with the
+      # same checkers as the project except for codeowners as this will not
+      # apply internally
       - name: Run Compliance Tests
         continue-on-error: true
         id: compliance
         env:
           BASE_REF: ${{ github.base_ref }}
         run: |
-          cd zephyrproject/zephyr
           export ZEPHYR_BASE=$PWD
-          # debug
-          ls -la
           git log  --pretty=oneline | head -n 10
           ./scripts/ci/check_compliance.py -m Devicetree -m Gitlint -m Identity -m Nits -m pylint -m checkpatch -m Kconfig -c origin/${BASE_REF}..
 
-      # Upload compliance.xml file to workflow run capturing any errors from the compliance check
+      # Upload compliance.xml file to workflow run capturing any errors from
+      # the compliance check
       - name: upload-results
         uses: actions/upload-artifact@master
         continue-on-error: True
         with:
           name: compliance.xml
-          path: zephyrproject/zephyr/compliance.xml
+          path: compliance.xml
 
-      # If there are no compliance errors then this step will pass, if failing then will also publish which errors were caught during the check
+      # If there are no compliance errors then this step will pass, if failing
+      # then will also publish which errors were caught during the check
       - name: check-warns
         run: |
-          cd zephyrproject/zephyr
           if [[ ! -s "compliance.xml" ]]; then
             exit 1;
           fi
